.github/workflows/0001-configure-test-flip-link-app-for-nrf52840.patch
.github/workflows/ci.yml

opening as PR to check if the CI runs actually run.
still missing: app-template stuff
closes https://github.com/knurling-rs/flip-link/issues/5 once it's done

add CI to build, check fmt and use in example app

---

.github/workflows/0001-configure-test-flip-link-app-for-nrf52840.patch
.github/workflows/ci.yml

~opening as PR to trigger ci builds.~
closes https://github.com/knurling-rs/flip-link/issues/7 ~once it's done~

optimize CI

---

src/main.rs

This change adds support for defining the RAM region's length as `10K + 10M`. This type of notation is used in the stm32f7xx-hal crate and flip-link failed with the message `MEMORY.RAM found after scanning linker scripts` which was also fixed to add the missing `not`.

Add support for section length arithmetic using + sign as used in stm32f7xx-hal crate.

---

src/main.rs

When the linker script with RAM location is in the root directory where you invoke `cargo` it is always used by the linker.
So only the beginning of the stack is changed which leads to an invalid memory layout.
When you look at the man page for GNU `ld` it says for the `-T` option:
> If scriptfile does not exist in the current directory, "ld" looks for it in the directories specified by any preceding -L options.
So it seems that this is also valid for included scripts.
As a first attempt to fix this problem I set the working dir for the second linker invocation to the temp dir containing the modified script. This works for my setup where I have a `memory.x` in the project root as well as for the example app in this repository.
It could be a problem though when you have multiple linker …

Problem with memory.x in the project root

---

tests/verify.rs

This PR verifies that the `initial stack-pointer` of each of the four example apps is inside the `static RAM` region, after being linked with `flip-link`.
I've made the choice to have one test for all example apps, instead of one test for each test. This approach is a bit easier to implement, but has the drawback of less error-resolution. E.g. if one of the examples would fail to compile the tests fail completely, instead of running the other ones successfully.
Depends on #40  and fixes #25.

Verify initial stack-pointer to be inside `static RAM`

---

xtest/src/main.rs

This makes sure that flip-link gets reinstalled, even if it is already
present on the system.

`xtest`: Pass `--force` to `cargo install`

---

Cargo.lock
Cargo.toml
src/linking.rs
src/main.rs

`tempfile` pulls in an amazing number of dependencies, which we don't really need just for storing a single linker script.
Note that I wasn't able to properly test this because the flip-link testsuite doesn't seem to work.

Avoid the `tempfile` dependency

---

src/main.rs

Should avoid cases like https://github.com/knurling-rs/flip-link/issues/57, where it looks like flip-link is the cause of an error.
Suggestions to improve the wording are welcome

Print a message when linking normally fails

---

src/main.rs

harmonize linker script directory search order with non-`flip-link` linkers to reduce surprises.
Specifically, other crates might introduce spurious and potentially wrong `memory.x` scripts, this PR attempts to do some damage control by searching the current working directory first

search linker scripts in cwd first

---

.github/workflows/ci.yml

time savings on cache hit
| Job             | before | after | after/before |
|-----------------|--------|-------|--------------|
| ubuntu-stable   | 105s   | 37s   |          35% |
| macos-stable    | 132s   | 68s   |          51% |
| windows-stable  | 176s   | 98s   |          55% |
| ubuntu-nightly  | 92s    | 40s   |          43% |
| macos-nightly   | 127s   | 65s   |          51% |
| windows-nightly | 163s   | 103s  |          63% |
don't ask me how to replicate the caching steps into the non-matrix job without copy-pasting the whole thing because I don't know :P

ci: cache cargo registry & build artifacts

---

.github/workflows/ci.yml
CHANGELOG.md

Install Rust manually in the CI, instead of relying on `actions-rs/toolchain`.
See https://github.com/knurling-rs/probe-run/issues/338.

CI: Install Rust manually

---

CHANGELOG.md
src/argument_parser.rs
src/main.rs

With https://github.com/knurling-rs/flip-link/commit/b7f556848a4f1c02b4f1987eb7fa5dbf95b995f6 comments in linker scripts were no longer ignored. This fixes that.
Closes https://github.com/knurling-rs/flip-link/issues/83

Ignore comments in linker script (fix)

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
test-flip-link-app/Cargo.toml

Fixes #82.
I tested the `pr-run-mode = "upload"` option to see if it builds successfully and it does: https://github.com/knurling-rs/flip-link/actions/runs/8177812280.
After merging this PR I will publish v0.1.8 and see if it works.
One question I have if it is possible that `cargo-dist` also publishes to crates.io when creating a release? But I will investigate this later.

Setup `cargo-dist`

---

.github/workflows/release-plz.yml
CHANGELOG.md

`release-plz` is based on `cargo-release` and maintains a Release PR, keeping it up-to-date as we merge additional commits. When we're ready to create a release, we simply merge the release PR.
It takes care of:
- CHANGELOG generation (with [git-cliff](https://git-cliff.org/)).
- Creation of GitHub releases. --> this will trigger `cargo-dist`
- Publishing to crates.io.
- Version bumps in Cargo.toml.
Read more https://github.com/MarcoIeni/release-plz.
**Todo**

Setup release-plz

---

.release-plz.toml
CHANGELOG.md

This PR changes two configurations.
Firstly it disables the changelog update. While this feature is generally desirable, git-cliff chokes on our git history and it is not trivial to configure it properly. Therefore this is deferred.
Secondly `cargo update` will be run.

Configure release-plz

---

CHANGELOG.md
README.md

Since Cargo [version 1.74], the linker can be selected without using `rustflags`. This way of setting it causes less conflict with other uses of `RUSTFLAGS`, which may need to be set outside `.cargo/config.toml`.
[version 1.74]: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-174-2023-11-16

Recommend `target.'cfg(..)'.linker` for recent Cargo versions

---

CHANGELOG.md
src/argument_parser.rs
src/main.rs

Fixes #95
I couldn't reproduce the original error I encountered, so I couldn't test if this works with rustc generated files, but based on the code for my initial fix, it should work. If someone can find a way to make rustc emit the at-file args so this can be properly tested, that would be great, but I'm very confident in it as it is.

Add support for @file args

---

CHANGELOG.md
src/main.rs

When use `flip-link` directly from command line, now flip-link returns an error code 1:
```
$ flip-link
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
flip-link: the native linker failed to link the program normally; please check your project configuration and linker scripts
```
It's inconvenient when we want to just test whether flip-link exists. In my case, I use `cargo-make` to automate the build workflow, it checks `flip-link` command's return code to determine whether to install the crate, so it will re-install flip-link everytime even though flip-link has been installed. 
This PR adds `-h`/`--help` argument. When user executes `flip-link -h` or `flip-link --help` or `flip-link` in command line, flip-link now …

Add support for -h/--help arg

---

.github/workflows/ci.yml

Instead of marking all individual jobs as required in the branch protection rules we can mark this one job, which depends on all other jobs, as required.

Add one job to mark as required for PRs

---

CHANGELOG.md
src/linking.rs
src/main.rs

When invoking flip-link in an environment where `rust-lld` is not in the path, we only get the rather unhelpful error message `Os { code: 2, kind: NotFound, message: "No such file or directory" }`.
With this PR, we report a more helpful error message that case, informing the user that whatever system linker is specified in linker.rs cannot be found.
This particular issue has been a pain point when using flip-link in an environment where we are also building rustc from source, and it took a while to realise needed to enable rust-lld when running cargo's `x.py` for flip-link to work.
Thank you!

Handle case where `rust-lld` is not in path

---

src/argument_parser.rs

I found this while trying to figure out how to write a "test case" for homebrew. They require a non-unit-test test, but also don't have the arm target available that I could use to compile `test-flip-link-app`. If you have any ideas those would be much appreciated!

Fix typo in `expand_files` documentation
